# Generated by Django 2.2.6 on 2020-03-06 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('summary', models.TextField(help_text='Enter a brief description', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='CollectionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('summary', models.TextField(help_text='Enter a brief description', max_length=1000)),
                ('opus', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CompositionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='composer',
            options={},
        ),
        migrations.AddField(
            model_name='composer',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Country'),
        ),
        migrations.CreateModel(
            name='Listening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('summary', models.TextField(help_text='Enter a brief description', max_length=1000)),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Collection')),
                ('composition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Composition')),
            ],
        ),
        migrations.AddField(
            model_name='composition',
            name='composer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Composer'),
        ),
        migrations.AddField(
            model_name='composition',
            name='compositioncategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.CompositionCategory'),
        ),
        migrations.AddField(
            model_name='collection',
            name='collectioncategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.CollectionCategory'),
        ),
    ]
