# Generated by Django 2.2.6 on 2020-03-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200306_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='composition',
            name='num_category',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='composition',
            name='num_opus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='collection',
            name='summary',
            field=models.TextField(help_text='Enter a brief description', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='composition',
            name='summary',
            field=models.TextField(help_text='Enter a brief description', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='listening',
            name='summary',
            field=models.TextField(help_text='Enter a brief description', max_length=1000, null=True),
        ),
    ]
