# Generated by Django 2.2.6 on 2020-03-06 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200306_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('summary', models.TextField(help_text='Enter a brief description', max_length=1000, null=True)),
                ('i_sequence', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='composition',
            old_name='num_category',
            new_name='i_category',
        ),
        migrations.RenameField(
            model_name='composition',
            old_name='num_opus',
            new_name='i_opus',
        ),
        migrations.CreateModel(
            name='PieceInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('summary', models.TextField(help_text='Enter a brief description', max_length=1000, null=True)),
                ('i_sequence', models.IntegerField(default=0)),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Collection')),
                ('piece', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Piece')),
            ],
        ),
        migrations.AddField(
            model_name='piece',
            name='composition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Composition'),
        ),
    ]
