# Generated by Django 2.2.6 on 2020-03-06 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200306_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composition',
            name='opus',
        ),
    ]
