# Generated by Django 2.2.6 on 2020-03-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_composition_opus'),
    ]

    operations = [
        migrations.AddField(
            model_name='composition',
            name='year',
            field=models.TextField(help_text='Enter a year', max_length=12, null=True),
        ),
    ]
