# Generated by Django 2.2.6 on 2020-03-06 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_composition_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composition',
            name='year',
        ),
    ]
