# Generated by Django 2.2.6 on 2020-03-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_composition_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pieceinstance',
            name='i_sequence',
        ),
        migrations.AlterField(
            model_name='collection',
            name='summary',
            field=models.TextField(blank=True, help_text='Enter a brief description', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='composition',
            name='summary',
            field=models.TextField(blank=True, help_text='Enter a brief description', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='listening',
            name='summary',
            field=models.TextField(blank=True, help_text='Enter a brief description', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='piece',
            name='summary',
            field=models.TextField(blank=True, help_text='Enter a brief description', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='pieceinstance',
            name='summary',
            field=models.TextField(blank=True, help_text='Enter a brief description', max_length=1000, null=True),
        ),
    ]
