# Generated by Django 2.2.6 on 2020-03-10 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20200310_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pieceinstance',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pieceinstance',
            name='summary',
        ),
    ]
