# Generated by Django 2.2.6 on 2020-03-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20200310_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listening',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
