# Generated by Django 2.2.6 on 2020-03-10 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20200310_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piece',
            name='summary',
        ),
    ]
