# Generated by Django 2.2.6 on 2020-03-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_remove_piece_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieceinstance',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
