# Generated by Django 2.2.6 on 2020-03-10 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_pieceinstance_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listening',
        ),
    ]
