# Generated by Django 2.2.6 on 2020-03-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_delete_listening'),
    ]

    operations = [
        migrations.AddField(
            model_name='composer',
            name='year_of_birth',
            field=models.CharField(default='', help_text='Year as text', max_length=12),
        ),
        migrations.AddField(
            model_name='composer',
            name='year_of_death',
            field=models.CharField(default='', help_text='Year as text', max_length=12),
        ),
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.ImageField(blank=True, default='a000.png', null=True, upload_to='images/'),
        ),
    ]
