# Generated by Django 2.2.6 on 2020-03-24 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20200324_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composer',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='composer',
            name='date_of_death',
        ),
    ]
